name: Generate Raw Links

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate README with raw links and curl commands
      run: |
        echo "# Raw File Links" > README.md
        echo "" >> README.md
        REPO="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}"

        find . -type f \
          ! -path "./.git/*" \
          ! -path "./README.md" \
          ! -path "./.github/*" | while read -r file; do
            raw_path="${file#./}"
            raw_url="${REPO}/${raw_path}"
            
            echo "## ${raw_path}" >> README.md
            echo "" >> README.md
            echo "[${raw_path}](${raw_url})" >> README.md
            echo "" >> README.md

            if [[ "${raw_path}" == *.sh ]]; then
              echo '```bash' >> README.md
              echo "bash <(curl -s ${raw_url})" >> README.md
              echo '```' >> README.md
              echo "" >> README.md
            fi
          done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README with raw links and run commands" || echo "No changes to commit"
        git push
